"""
Read and interpret C2PA / Content Credentials manifests using the official
c2pa-python SDK (Rust-backed, platform wheel for Windows/macOS/Linux).

This replaces naive byte-signature "does a C2PA blob exist" detection with an
actual parsed, validated manifest read: who/what claims to have produced the
image, and — critically — the IPTC `digitalSourceType` on each action, which
is the standardized field that distinguishes a real camera capture
(e.g. "digitalCapture") from AI-generated content
(e.g. "trainedAlgorithmicMedia", "compositeSynthetic").

API usage verified against the real c2pa-python docs (Context7:
/contentauth/c2pa-python) rather than assumed:
  - Reader.try_create(path) returns None (not an exception) when there's no
    manifest -- the documented way to avoid catching ManifestNotFound.
  - reader.get_validation_state() returns "Valid" / "Invalid" / None directly;
    there is no "validation_state" key to guess at in the JSON.
  - json() returns a JSON string: {"active_manifest": "...", "manifests": {...}}
  - C2paError has typed subclasses (ManifestNotFound, Verify, Signature, etc.)
    accessible as C2paError.X, which we catch specifically instead of
    string-matching a generic Exception's message.

Optional dependency: c2pa-python. If not installed, every function here
degrades to returning {"available": False, ...} rather than raising, so the
rest of raven works identically without it.
"""
from __future__ import annotations
import json as _json
from typing import Optional

try:
    from c2pa import Reader, C2paError
    _C2PA_AVAILABLE = True
except ImportError:
    _C2PA_AVAILABLE = False

# IPTC digitalSourceType URIs that indicate synthetic/AI-generated origin.
# Reference: https://cv.iptc.org/newscodes/digitalsourcetype/
_AI_SOURCE_TYPES = {
    "trainedalgorithmicmedia",   # wholly generated by a trained algorithm (typical genAI)
    "compositesynthetic",        # synthetic composite (e.g. AI inpainting/outpainting)
    "algorithmicmedia",          # produced algorithmically, not by direct human capture
    "digitalcreation",           # created directly using digital tools (often generative)
}
# IPTC digitalSourceType URIs that indicate a real capture device.
_CAPTURE_SOURCE_TYPES = {
    "digitalcapture", "negativefilm", "positivefilm", "print",
    "minorhumanedits", "compositecapture",
}


def is_available() -> bool:
    return _C2PA_AVAILABLE


def read_c2pa_manifest(path: str) -> dict:
    """
    Returns:
        {
          "available": bool,           # whether c2pa-python is installed
          "present": bool,              # whether a manifest was found in this file
          "valid": Optional[bool],      # True/False from get_validation_state(), None if unknown
          "claim_generator": str|None,  # e.g. "Adobe Photoshop", "ChatGPT"
          "software_agents": [str,...], # every softwareAgent named in actions
          "digital_source_types": [str,...],
          "ai_generated": Optional[bool],   # True/False if a digitalSourceType resolved it, else None
          "error": str|None,
        }
    """
    result = {
        "available": _C2PA_AVAILABLE,
        "present": False,
        "valid": None,
        "claim_generator": None,
        "software_agents": [],
        "digital_source_types": [],
        "ai_generated": None,
        "error": None,
    }
    if not _C2PA_AVAILABLE:
        return result

    try:
        reader = Reader.try_create(path)
    except C2paError as e:
        result["error"] = f"{type(e).__name__}: {e}"
        return result
    except Exception as e:
        # Belt-and-suspenders: a non-C2paError shouldn't happen per the docs,
        # but never let an unexpected exception type break the whole scan.
        result["error"] = f"{type(e).__name__}: {e}"
        return result

    if reader is None:
        return result  # no manifest present; not an error

    try:
        with reader:
            validation_state = reader.get_validation_state()
            store = _json.loads(reader.json())
    except C2paError as e:
        result["error"] = f"{type(e).__name__}: {e}"
        return result
    except Exception as e:
        result["error"] = f"manifest_parse: {type(e).__name__}: {e}"
        return result

    active_id = store.get("active_manifest")
    manifests = store.get("manifests", {})
    manifest = manifests.get(active_id) if active_id else next(iter(manifests.values()), None)
    if not manifest:
        return result

    result["present"] = True
    if validation_state in ("Valid", "Invalid"):
        result["valid"] = (validation_state == "Valid")

    gens = manifest.get("claim_generator_info") or []
    if gens:
        result["claim_generator"] = gens[0].get("name")
    elif manifest.get("claim_generator"):
        result["claim_generator"] = manifest["claim_generator"]

    agents: list[str] = []
    source_types: list[str] = []
    for assertion in manifest.get("assertions", []):
        label = assertion.get("label", "")
        if label.startswith("c2pa.actions"):
            for action in (assertion.get("data", {}) or {}).get("actions", []):
                agent = action.get("softwareAgent")
                if isinstance(agent, dict):
                    agent = agent.get("name")
                if agent:
                    agents.append(str(agent))
                dst = action.get("digitalSourceType")
                if dst:
                    source_types.append(dst)

    result["software_agents"] = sorted(set(agents))
    result["digital_source_types"] = sorted(set(source_types))

    # Resolve ai_generated from the standardized IPTC source-type URIs; this is
    # the one field in the whole manifest that's explicitly designed to answer
    # this question, so we trust it over freeform tool-name string matching.
    lowered = {t.rsplit("/", 1)[-1].lower() for t in source_types}
    if lowered & _AI_SOURCE_TYPES:
        result["ai_generated"] = True
    elif lowered & _CAPTURE_SOURCE_TYPES:
        result["ai_generated"] = False

    return result
